"""Create All Tables updations

Revision ID: fdb5c3c6ce2b
Revises: 
Create Date: 2026-02-25 00:55:54.185982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb5c3c6ce2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_type',
    sa.Column('exam_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('exam_type_id')
    )
    op.create_table('grade',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('desc', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_table('parent',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('fname', sa.String(length=45), nullable=False),
    sa.Column('lname', sa.String(length=45), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('fname', sa.String(length=45), nullable=False),
    sa.Column('lname', sa.String(length=45), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('classroom',
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=45), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.grade_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('classroom_id')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.grade_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('exam',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_type.exam_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('fname', sa.String(length=45), nullable=False),
    sa.Column('lname', sa.String(length=45), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('date_of_join', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.parent_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attendance',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date', 'student_id')
    )
    op.create_table('classroom_student',
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.classroom_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classroom_id', 'student_id')
    )
    op.create_table('exam_result',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('marks', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'student_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_result')
    op.drop_table('classroom_student')
    op.drop_table('attendance')
    op.drop_table('student')
    op.drop_table('exam')
    op.drop_table('course')
    op.drop_table('classroom')
    op.drop_table('teacher')
    op.drop_table('parent')
    op.drop_table('grade')
    op.drop_table('exam_type')
    # ### end Alembic commands ###
